### ISSUE TITLE
not supported inside vehicle

### ISSUE THREAD

**Issue by iamjexcdevvv** [devbluen/WazeGPS-Samp#3]
what's the reason why it doesn't support when the player is inside of any vehicle?

```c
if(IsPlayerInAnyVehicle(playerid)) return true;

**Comment by iamjexcdevvv** [comment]
also i've noticed that when the player exits a vehicle the marker or the waze thing disappeared

**Comment by devbluen** [comment]
This went unnoticed, it was a test that ended up remaining, the repository was updated removing this check.
Thanks for the report.

**Comment by devbluen** [comment]
https://github.com/devbluen/WazeGPS-Samp/releases/tag/V.1404
Fix
