### ISSUE TITLE
Function not registered

### ISSUE THREAD

**Issue by y-strider** [devbluen/WazeGPS-Samp#4]
[Error] Function not registered: GetPathNodeIndex
[Error] Function not registered: GetPathNode
[Error] Function not registered: GetMapNodePos
[Error] Function not registered: GetPathLength
[Error] Function not registered: GetPathSize
[Error] Function not registered: IsValidPath
[Error] Function not registered: FindPathThreaded
[Error] Function not registered: GetClosestMapNodeToPoint

latest V.1404

**Comment by y-strider** [comment]
and the script isn't working

**Comment by y-strider** [comment]
[Info] [debug] #1 00003a9c in SetPlayerWaze (playerid=0, Float:x=1682.21997, Float:y=-2261.04004, Float:z=13.51000, color=-1975196417) at C:\Users\admin\OneDrive\Desktop\CDP\qawno\include\WazeGPS.inc:62
[Info] [debug] #2 00023360 in public pc_cmd_setgps (playerid=0, params[]=@00109884 "0 1682.22 -2261.04 13.51") at C:\Users\admin\OneDrive\Desktop\CDP\gamemodes\ciudadparaiso.pwn:1558
[Info] [Pawn.CMD] Array index out of bounds in public pc_cmd_setgps(0, "0 1682.22 -2261.04 13.51") - please note that the AMX error is not related with the plugin, but your script
[Info] [debug] Long callback execution detected (hang or performance issue)

**Comment by y-strider** [comment]
[Info] [debug] #0 0000bba0 in DestroyWazeRoutesGPS (playerid=0) at .pwn:597
 [Info] [debug] #1 00012a98 in public OnPlayerWazeRouters (Path:pathid=17, playerid=0) at .pwn:785
 [Info] [debug] Run time error 4: "Array index out of bounds"

**Comment by devbluen** [comment]
> [Error] Function not registered: GetPathNodeIndex [Error] Function not registered: GetPathNode [Error] Function not registered: GetMapNodePos [Error] Function not registered: GetPathLength [Error] Function not registered: GetPathSize [Error] Function not registered: IsValidPath [Error] Function not registered: FindPathThreaded [Error] Function not registered: GetClosestMapNodeToPoint
> 
> latest V.1404

Hello. You need to include the GPS plugin in server.cfg and add GPS.dat within scriptfiles for everything to happen successfully.

**Comment by devbluen** [comment]
> [Info] [debug] #0 0000bba0 in DestroyWazeRoutesGPS (playerid=0) at .pwn:597 [Info] [debug] #1 00012a98 in public OnPlayerWazeRouters (Path:pathid=17, playerid=0) at .pwn:785 [Info] [debug] Run time error 4: "Array index out of bounds"

Perhaps it is not a system error itself, as the debug itself shows, the playerid did not exceed id 0 and the pathid is also within the correct range. Check your code and if the problem persists, let me know again.

**Comment by y-strider** [comment]
how abot this i remove the YSI files cuz i dunno use YSI_libraries

[Info] [debug] #0 00014098 in public SSCANF_OnGameModeInit ()  at C:\CDP\gamemodes\ciudadparaiso.pwn:882 // this line isn't specific line
[Info] [debug] #1 00002168 in public Iter_OnGameModeInit () at C:\CDP\qawno\include\sscanf2.inc:1254 // SSCANF_OnGameModeInit();
[Info] [debug] #2 native CallLocalFunction () in Pawn.dll
[Info] [debug] #3 00001280 in public PawnCmd_OnGameModeInit () at C:\CDP\qawno\include\foreach.inc:751 // CallLocalFunction(YSI_gsOnGameModeInit, YSI_gsSpecifier@);

**Comment by iamjexcdevvv** [comment]
[11:05:28] Long callback execution detected (hang or performance issue)
[11:05:28] AMX backtrace:
[11:05:28] #0 000a45cc in Float:GDBP (Float:X=1537.62500, Float:Y=-1671.37500, Float:Z=0.00000, Float:PointX=1537.12500, Float:PointY=-1678.37500, Float:PointZ=0.00000) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:165
[11:05:28] #1 000a5018 in CreateWazePointer (playerid=0, Float:X1=1537.62500, Float:Y1=-1671.37500, Float:X2=1537.12500, Float:Y2=-1678.37500, color=0) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:215
[11:05:28] #2 000a4528 in public OnPlayerWazeRouters (0, 0) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:145
[11:05:43] Long callback execution detected (hang or performance issue)
[11:05:43] AMX backtrace:
[11:05:43] #0 000a4f70 in CreateWazePointer (playerid=0, Float:X1=1529.50000, Float:Y1=-1627.75000, Float:X2=1529.50000, Float:Y2=-1627.75000, color=0) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:213
[11:05:43] #1 000a4528 in public OnPlayerWazeRouters (1, 0) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:145
[11:05:43] Run time error 4: "Array index out of bounds"
[11:05:43]  Attempted to read/write array element at negative index -2147483648
[11:05:43] AMX backtrace:
[11:05:43] #0 000a53b0 in CreateWazePointer (playerid=0, Float:X1=797.87500, Float:Y1=-1209.62500, Float:X2=797.37500, Float:Y2=-1190.12500, color=0) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:236
[11:05:43] #1 000a4528 in public OnPlayerWazeRouters (1, 0) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:145

@devbluen

**Comment by devbluen** [comment]
> [11:05:28] Long callback execution detected (hang or performance issue) [11:05:28] AMX backtrace: [11:05:28] #0 000a45cc in Float:GDBP (Float:X=1537.62500, Float:Y=-1671.37500, Float:Z=0.00000, Float:PointX=1537.12500, Float:PointY=-1678.37500, Float:PointZ=0.00000) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:165 [11:05:28] #1 000a5018 in CreateWazePointer (playerid=0, Float:X1=1537.62500, Float:Y1=-1671.37500, Float:X2=1537.12500, Float:Y2=-1678.37500, color=0) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:215 [11:05:28] #2 000a4528 in public OnPlayerWazeRouters (0, 0) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:145 [11:05:43] Long callback execution detected (hang or performance issue) [11:05:43] AMX backtrace: [11:05:43] #0 000a4f70 in CreateWazePointer (playerid=0, Float:X1=1529.50000, Float:Y1=-1627.75000, Float:X2=1529.50000, Float:Y2=-1627.75000, color=0) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:213 [11:05:43] #1 000a4528 in public OnPlayerWazeRouters (1, 0) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:145 [11:05:43] Run time error 4: "Array index out of bounds" [11:05:43] Attempted to read/write array element at negative index -2147483648 [11:05:43] AMX backtrace: [11:05:43] #0 000a53b0 in CreateWazePointer (playerid=0, Float:X1=797.87500, Float:Y1=-1209.62500, Float:X2=797.37500, Float:Y2=-1190.12500, color=0) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:236 [11:05:43] #1 000a4528 in public OnPlayerWazeRouters (1, 0) at C:\Users\admin\Desktop\project-gamemode\qawno\include\WazeGPS.inc:145
> 
> @devbluen

Yeah, the iterator added in the last updates turned out to be a problem, I will do an update today to fix it.

**Comment by devbluen** [comment]
https://github.com/devbluen/WazeGPS-Samp/releases/tag/V.1405
Test this new version, if you continue to have problems let me know.
